### ISSUE TITLE
Which seines from doubled effort to include?

### ISSUE THREAD

**Issue by salmonsam** [HakaiInstitute/jsp-time-series#13]
In the data_wrangle file, under the 'Migration Timing' chunk, you've removed the doubled up seines from the intensive sampling period. I'm just curious if you tried calculating catch/cumulative abundance using the opposite set of seines from that period and if it made any difference to the numbers/timing?

**Comment by Br-Johnson** [comment]
I haven't done anything other than remove the addittional seines:

https://github.com/HakaiInstitute/jsp-time-series/blob/b4f46e4addbf718f828bb356c3980e727b171042/scripts/data_wrangle.Rmd#L400

**Comment by Br-Johnson** [comment]
There needs to be some thought given to how to deal with these additional seines given that the cumulative abundance migration timing method relies on consistent effort within each season. 

Perhaps resampling half the seines within our doubled effort period 1000 times to create an empirical distribution of catch abundances and then from that take a mean total catch for each species is the best way forward.

**Comment by Br-Johnson** [comment]
Salmon Sam isn't working on this anymore. And in our last meeting, we discussed that re-sampling isn't needed. Likely we just need to average the catch of each species from the same site in the same week. @sarah-friesen are you keen to take this on?

**Comment by jclgan** [comment]
Averaged the catch totals of the double-effort seines from 2019 so that sampling effort is treated as consistent within the year
