### ISSUE TITLE
Should we still consider D34 even though it was only sampled in 2017?

### ISSUE THREAD

**Issue by jclgan** [HakaiInstitute/jsp-time-series#16]
Especially since it's a tertiary site to D08, and now we have D35 as our new secondary to D10/E

https://github.com/HakaiInstitute/jsp-time-series/blob/28013b6ff4119a3c30edacc5440f615a33b191f9/scripts/data_wrangle.Rmd#L42

**Comment by Br-Johnson** [comment]
I don't think we caught fish there often (maybe once?). Throwing out D34 data means poorer coverage for the already data deficient eastern zone...
