### ISSUE TITLE
Survey date restricted for 2015-18 data but not for 2019 data

### ISSUE THREAD

**Issue by jclgan** [HakaiInstitute/jsp-time-series#17]
https://github.com/HakaiInstitute/jsp-time-series/blob/28013b6ff4119a3c30edacc5440f615a33b191f9/scripts/data_wrangle.Rmd#L54

Why is this filter applied only to 2015-2018 data, but not for 2019 (in code that has yet to be pushed to master)?

**Comment by Br-Johnson** [comment]
The same filter of date ranges should apply to all years. Feel free to fix the code that reads in 2019 data from the 2019 field data google sheets. When we read all the data from one set of .csv files we can apply the filter once to all years.

**Comment by jclgan** [comment]
Fixed after merge of feature/julianwrangle
