### ISSUE TITLE
Averaging Temperatures Across Top 20 m?

### ISSUE THREAD

**Issue by sarah-friesen** [HakaiInstitute/jsp-time-series#18]
During our last meeting, we talked about restricting our oceanography data to the top 20 m instead of the top 30 m before calculating temperature averages, but I don't think we decided either way. The mean temperature difference between using the top 20 m instead of 30 m to calculate the daily temperature averages for each site is below. Thoughts?
js2_12     +0.058
QU29     +0.015
QU39     +0.338

**Comment by Br-Johnson** [comment]
I think 30 m is conservative. There are a number of potential problems with arbitrarily using 30 m though. Ideally, we would use a 1021 kg/m^3 density pycnocline which would be targetting surface waters. I think for the purposes of this report, however, the top 30 m is fine.
