### ISSUE TITLE
Update sites that are used in all time series calcs

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/jsp-time-series#2]
Currently we are missing some sites that were sampled in 2019 but not other years. We need to have a close look at which sites have been used in the past (and that we all agree those make sense), and decide which sites to use this year (likely all the sites we surveyed?)

**Comment by Br-Johnson** [comment]
I'll have a closer look at sites used and then by next meeting present my rationale for what sites were used.

See https://github.com/HakaiInstitute/jsp-time-series/blob/28013b6ff4119a3c30edacc5440f615a33b191f9/scripts/data_wrangle.Rmd#L27

**Comment by jclgan** [comment]
Added D35; otherwise, unchanged.
