### ISSUE TITLE
Visualizing average temperature across time series

### ISSUE THREAD

**Issue by sarah-friesen** [HakaiInstitute/jsp-time-series#22]
Hey @Br-Johnson, I am wondering about the regressions you used in Figure 9 of last year's report (details below). My assumption is that the difference arises from using an increment of 1/10 of a day in the first regression. In your mind, which one makes more sense to use?

First, a loess regression is applied to the daily average temperature values at QU39 across all years to generate a smooth predicted temperature curve. This is the black line that lines up with the edges of the areas in the figure below
[https://github.com/HakaiInstitute/jsp-time-series/blob/28013b6ff4119a3c30edacc5440f615a33b191f9/scripts/data_wrangle.Rmd#L884-L899](url)

The daily average temperatures for QU39 are added to a table with all temperatures for all sites…
[https://github.com/HakaiInstitute/jsp-time-series/blob/28013b6ff4119a3c30edacc5440f615a33b191f9/scripts/data_wrangle.Rmd#L1067](url)

...and filtered back down to only QU39 daily average temperatures. Then geom_smooth applies a loess regression, which is the line that shows standard error in the figure below
[https://github.com/HakaiInstitute/jsp-time-series/blob/28013b6ff4119a3c30edacc5440f615a33b191f9/scripts/Migration_Observations_Report.Rmd#L640-L655](url)

![sst](https://user-images.githubusercontent.com/28276069/66090860-05390e80-e53a-11e9-906f-cd6696f99f3b.png)

**Comment by Br-Johnson** [comment]
The difference is the result of a rather arbitrary difference in the span parameter which determines how far along the x axis values affect the regression.
