### ISSUE TITLE
Pink in Odd Years?

### ISSUE THREAD

**Issue by salmonsam** [HakaiInstitute/jsp-time-series#3]
I understand why we're only looking at cumulative pink catches in even years, but it might be worth comparing to odd years? Or standardizing abundance in some way so that we can include odd years? (in data_wrangle.Rmd)

**Comment by sarah-friesen** [comment]
I feel like it would be worth including odd years for pink cumulative catch in the migration timing plot as well

**Comment by Br-Johnson** [comment]
Because most of the pinks in odd years aren't Fraser stocks (we assume), I don't think it makes sense to include odd years in migration timing because of unknown residency patterns in the Discovery Islands versus the punctuated migration timing we expect out of the SoG into the Discovery Islands.
