### ISSUE TITLE
set type : Targeted/random survey seines

### ISSUE THREAD

**Issue by saratrem** [HakaiInstitute/jsp-time-series#4]
I noticed the survey_seines only includes "targeted" sets. Do we want to include random sets as well? or there is a reason behind ?  

In 2018 (didn't look at any other year) - we collected fish with "random" set 3 times, retaining 47 fish in total. those are not included in the data right now.

**Comment by Br-Johnson** [comment]
I think it's best to leave out 'random' sets to ensure that our seines remain comparable. Random sets would have a lower probability of catching fish and would bias our catch abundance low.
