### ISSUE TITLE
Cumulative catch vs abundance

### ISSUE THREAD

**Issue by sarah-friesen** [HakaiInstitute/jsp-time-series#6]
Is cumulative catch a reasonable proxy for abundance? Is it a reasonable proxy at least for relative abundance?

**Comment by Br-Johnson** [comment]
Precedent set in DFO SoG residency period paper by Neville et al. 2016 'Initial estimates...' 

Important to be clear in discussion and figures that we are basing our migration timing on the median date of the relative abundance of certain species. Define relative abundance clearly in report.
