### ISSUE TITLE
Chinook and species proportions

### ISSUE THREAD

**Issue by sarah-friesen** [HakaiInstitute/jsp-time-series#9]
I understand that Chinook are very uncommon in our catches, so the species proportion calculations are likely unchanged whether Chinook is considered or not. But to me, it makes sense to include Chinook in the proportion calculations/figure in order to demonstrate this, rather than excluding Chinook since that could also indicate that we excluded Chinook from our sampling efforts completely. Perhaps there is something here that I missed though?

**Comment by Br-Johnson** [comment]
We didn't retain or enumerate chinook in 2015 and 16 so we cant make inter-annual comparisons.
